#
# ~/.bashrc
#

[[ $- != *i* ]] && return
alias ls='ls --color=auto'
#PS1="\[\e[35m\][\[\e[m\]\[\e[35m\]\u\[\e[m\]\[\e[35m\]@\[\e[m\]\[\e[35m\]\h\[\e[m\]\[\e[35m\] \[\e[m\]\[\e[35m\]\W\[\e[m\]\[\e[35m\]]\[\e[m\]\[\e[33m\]\\$\[\e[m\] "
PS1="[\u@\h \W]\\$ "
#PS1="[\u@\h \W]\[\e[33m\]\\$\[\e[m\] "
PATH="$HOME/.local/bin:$PATH"
alias sx='startx'
alias off='sudo shutdown now'
alias connect-android="simple-mtpfs --device 1 fi/media"
alias c='clear'
alias aur='pikaur'
